// Rules that hold whatever the repository is written in.
export const core = [
  {
    id: "force-push",
    description: "Any force push to any branch",
    severity: "critical",
    when: { forced: true },
  },
  {
    id: "trojan-source",
    description: "Source that renders differently than it executes: bidi overrides, invisible characters",
    severity: "critical",
    unicode_risk: "controls",
  },
  {
    id: "homoglyph-identifier",
    description: "A character from another script sitting inside an otherwise Latin identifier",
    severity: "high",
    unicode_risk: "confusables",
    enabled: false,
  },
  {
    id: "hidden-by-padding",
    description: "A line indented far enough to push its code out of view in a diff",
    severity: "high",
    added_lines: "^[ \\t]{200,}",
  },
  {
    id: "impersonated-commit",
    description: "A commit claiming another account's authorship reached a branch without review",
    severity: "critical",
    when: { author_mismatch: true, unreviewed: true },
  },
  {
    id: "fake-merge-commit",
    description: "A commit says it merged a pull request, and no pull request contains it",
    severity: "critical",
    commit_message: "^Merge pull request #\\d+",
    when: { unreviewed: true },
  },
  {
    id: "unreviewed-push-to-main",
    description: "Code reached a protected branch without a pull request",
    severity: "high",
    branches: ["main", "master", "release/*", "develop"],
    when: { unreviewed: true },
    enabled: false,
  },
  {
    id: "first-push-by-account",
    description: "An account pushed to this repository for the first time",
    severity: "medium",
    when: { sender_first_push: true },
  },
  {
    id: "branch-deleted",
    description: "Branch deleted on a protected-pattern name",
    severity: "medium",
    branches: ["main", "master", "release/*"],
    when: { branch_deleted: true },
  },
  {
    id: "off-hours-push",
    description: "Push outside 04:00-18:00 UTC working window",
    severity: "low",
    branches: ["main", "master"],
    when: { hour_utc: { not_between: [4, 18] } },
  },
  {
    id: "protection-removed",
    description: "Workflow, CODEOWNERS, or hook config deleted",
    severity: "critical",
    paths: [
      ".github/workflows/**",
      "CODEOWNERS",
      ".github/CODEOWNERS",
      "docs/CODEOWNERS",
      ".husky/**",
      ".pre-commit-config.yaml",
    ],
    change_type: ["removed"],
  },
  {
    id: "reviewers-and-ci-in-one-push",
    description: "One push changed both the review rules and the CI that runs with your secrets",
    severity: "critical",
    all_of: [
      ["CODEOWNERS", ".github/CODEOWNERS", "docs/CODEOWNERS", ".github/**/CODEOWNERS"],
      [".github/workflows/**"],
    ],
  },
  {
    id: "env-file-committed",
    description: "Dotenv file pushed to the repo",
    severity: "critical",
    paths: ["**/.env", "**/.env.*"],
    exclude_paths: ["**/.env.example", "**/.env.sample", "**/.env.template"],
    change_type: ["added", "modified"],
  },
  {
    id: "editor-autorun-changed",
    description: "Editor config that runs commands on open was modified",
    severity: "high",
    paths: [
      ".vscode/tasks.json",
      ".vscode/settings.json",
      ".vscode/launch.json",
      ".idea/**/*.xml",
      ".devcontainer/**",
    ],
  },
  {
    id: "git-hooks-added",
    description: "A git hook or hooks path that runs on ordinary git commands",
    severity: "critical",
    paths: [".githooks/**", ".husky/**", "**/.git/hooks/**"],
    change_type: ["added", "modified"],
  },
  {
    id: "gitattributes-filter",
    description: "A .gitattributes filter, which runs a command on checkout",
    severity: "high",
    paths: ["**/.gitattributes"],
    added_lines: "filter=",
  },
] as const
